Kombin/Controllers/LoginController.cs
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Kombin.Controllers
{

    public class LoginController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Index(User user)
        {
            using (var sha256provider = new SHA256CryptoServiceProvider())
            {
                var hash = sha256provider.ComputeHash(Encoding.UTF8.GetBytes(user.UserPassword));
                user.UserPassword = BitConverter.ToString(hash).Replace("-", "");
            }

            Context context = new Context();
            var dataValue = context.Users.FirstOrDefault(x => x.UserUsername == user.UserUsername && x.UserPassword == user.UserPassword);


            if (dataValue != null)
            {

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,user.UserUsername),
                    new Claim(ClaimTypes.Role, "Admin"),
                    new Claim("userid".ToString(),dataValue.UserId.ToString()),
                };

                HttpContext.Session.SetString("userid", dataValue.UserId.ToString());

                var userIdentity = new ClaimsIdentity(claims, "a");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Home");
            }
            else
            {

                return View();
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            return View();
        }
    }
}

Kombin/Controllers/RegisterController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Kombin.Controllers
{
    public class RegisterController : Controller
    {

        UserManager userManager = new UserManager(new EfUserRepository());

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        public IActionResult Index(User user)
        {
            user.Role = 1;

            using (var sha256provider = new SHA256CryptoServiceProvider())
            {
                var hash = sha256provider.ComputeHash(Encoding.UTF8.GetBytes(user.UserPassword));
                user.UserPassword = BitConverter.ToString(hash).Replace("-", "");
            }

            userManager.Add(user);
            return RedirectToAction("Index", "Home");
            //return View();
        }

    }
}

Kombin/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@using Microsoft.AspNetCore.Http;
@using DataAccessLayer.Concrete;

@{
    string userId = null;
    if (HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
    {
        string user = HttpContextAccessor.HttpContext.User.FindFirst("userid").Value;
        userId = HttpContextAccessor.HttpContext.Session.GetString("userid");
        userId = user;
        if (userId != null)
        {
            Context context = new Context();
            var loggedUser = context.Users.Find(Convert.ToInt32(user));
            ViewBag.loggedUserName = loggedUser.UserFullname;
            ViewBag.loggedUserId = userId;
            ViewBag.loggedUserRole = loggedUser.Role;
        }
    }
    /*
    var userId = HttpContextAccessor.HttpContext.Session.GetString("userid");
    if (userId != null)
    {
        Context context = new Context();
        var loggedUser = context.Users.Find(Convert.ToInt32(user));
        ViewBag.loggedUserName = loggedUser.UserFullname;
        ViewBag.loggedUserId = userId;
        ViewBag.loggedUserRole = loggedUser.Role;
    }
    */
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kombin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="Stylesheet" type="text/css" href="~/css/dropdown.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kombin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Man">Erkek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Woman">Kadın</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Explore">Keşfet</a>
                        </li>

                    </ul>
                </div>
                <div class="collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li>
                            <div class="dropdown">
                                @if (userId == null)
                                {
                                    <button class="btn btn-secondary dropdown-toggle"
                                            type="button" id="dropdownMenu1" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                        Guest
                                    </button>

                                }
                                else
                                {
                                    <button class="btn btn-secondary dropdown-toggle"
                                            type="button" id="dropdownMenu1" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                        @ViewBag.loggedUserName
                                    </button>
                                }

                                @if (ViewBag.loggedUserId != null)
                                {
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        @if (ViewBag.loggedUserRole == 0)
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="AdminPanel" asp-action="Index">Admin Panel</a>
                                        }
                                        <a class="dropdown-item" asp-area="" asp-controller="Post" asp-action="Index" style="border-style: solid; background-color: #fff;">Kombinlerim</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout" style="border-style: solid; background-color: #fff;">Çıkış Yap</a>
                                    </div>
                                }
                                else
                                {
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <a class="dropdown-item" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                    </div>
                                }
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Kombin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>